version: '3.4'

services:
  webrtc:
    image: ${DOCKER_REGISTRY-}comruivopwebrtc
    build:
      context: .
      dockerfile: com.ruivop.webrtc/Dockerfile
    ports:
      - "49154:80"

  nginxswag:
    depends_on:
      - webrtc
    image: linuxserver/swag:version-1.11.0
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=ruivop.com
      - SUBDOMAINS=sierscan,
      - VALIDATION=http
      - EMAIL=ruivascoliveirapaiva@hotmail.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf/apprestapi.subdomain.conf:/config/nginx/site-confs/default